In [1]:
#sort ,search & counting function

In [2]:
import numpy as np

In [4]:
arr = np.array([4,2,4,78,9,356,242,63,26,647,4,7])

In [5]:
arr

array([  4,   2,   4,  78,   9, 356, 242,  63,  26, 647,   4,   7])

In [6]:
np.sort(arr)

array([  2,   4,   4,   4,   7,   9,  26,  63,  78, 242, 356, 647])

In [8]:
np.searchsorted(arr ,10)

3

In [9]:
arr1 = np.array([0,242,466,12,66,0,0,0,0,0])

In [10]:
np.count_nonzero(arr1)

4

In [11]:
arr

array([  4,   2,   4,  78,   9, 356, 242,  63,  26, 647,   4,   7])

In [12]:
np.where(arr>10)

(array([3, 5, 6, 7, 8, 9]),)

In [13]:
np.extract(arr<6 , arr)

array([4, 2, 4, 4])

In [15]:
#numpy - Byte swapping

In [16]:
arr.byteswap()

array([  288230376151711744,   144115188075855872,   288230376151711744,
        5620492334958379008,   648518346341351424,  7206040878769504256,
       -1008806316530991104,  4539628424389459968,  1873497444986126336,
       -8718405928635858944,   288230376151711744,   504403158265495552])

In [18]:
#numpy-copies &view

In [19]:
arr

array([  4,   2,   4,  78,   9, 356, 242,  63,  26, 647,   4,   7])

In [17]:
a = np.copy(arr)

In [20]:
b = arr.view()

In [21]:
b

array([  4,   2,   4,  78,   9, 356, 242,  63,  26, 647,   4,   7])

In [23]:
b[0] = 99

In [24]:
b

array([ 99,   2,   4,  78,   9, 356, 242,  63,  26, 647,   4,   7])

In [25]:
arr

array([ 99,   2,   4,  78,   9, 356, 242,  63,  26, 647,   4,   7])

In [26]:
#numpy - matrix liberary

In [27]:
import numpy.matlib as nm 

In [28]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [29]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [30]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [31]:
#numpy - linear algebra

In [33]:
arr1 = np.random.randint([[2,3] , [4,5]])

In [34]:
arr2 = np.random.randint([[2,3] , [4,5]])

In [35]:
np.dot(arr1 , arr2)

array([[ 6,  8],
       [12, 12]])

In [36]:
arr1@arr2

array([[ 6,  8],
       [12, 12]])