In [3]:
#numpy - array manipulation

In [4]:
import numpy as np 

In [5]:
arr =  np.random.randint(1,10 , (3,4))

In [6]:
arr

array([[2, 3, 7, 6],
       [7, 5, 5, 6],
       [7, 5, 4, 4]])

In [7]:
arr.reshape(6,2)

array([[2, 3],
       [7, 6],
       [7, 5],
       [5, 6],
       [7, 5],
       [4, 4]])

In [8]:
arr.reshape(2,6)

array([[2, 3, 7, 6, 7, 5],
       [5, 6, 7, 5, 4, 4]])

In [9]:
arr.T

array([[2, 7, 7],
       [3, 5, 5],
       [7, 5, 4],
       [6, 6, 4]])

In [10]:
arr.flatten()

array([2, 3, 7, 6, 7, 5, 5, 6, 7, 5, 4, 4])

In [11]:
arr1 = np.array([1,2,3,4,3,4])

In [13]:
arr1.ndim

1

In [15]:
np.expand_dims(arr1 , axis = 1)

array([[1],
       [2],
       [3],
       [4],
       [3],
       [4]])

In [16]:
np.expand_dims(arr1 , axis = 0)

array([[1, 2, 3, 4, 3, 4]])

In [17]:
arr

array([[2, 3, 7, 6],
       [7, 5, 5, 6],
       [7, 5, 4, 4]])

In [18]:
np.squeeze(arr)

array([[2, 3, 7, 6],
       [7, 5, 5, 6],
       [7, 5, 4, 4]])

In [19]:
data = np.array([[1] , [2] , [3]])

In [20]:
data

array([[1],
       [2],
       [3]])

In [21]:
np.squeeze(data)

array([1, 2, 3])

In [22]:
arr1

array([1, 2, 3, 4, 3, 4])

In [23]:
np.repeat(arr1, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 3, 3, 3, 4, 4, 4])

In [25]:
np.roll(arr1 , 2)

array([3, 4, 1, 2, 3, 4])

In [26]:
arr1

array([1, 2, 3, 4, 3, 4])

In [27]:
np.diag(arr1)

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 3, 0],
       [0, 0, 0, 0, 0, 4]])

In [28]:
#numpy - Binary operation

In [30]:
arr1 = np.random.randint(1,10 , (3,4))

In [32]:
arr2 = np.random.randint(1,10 , (3,4))

In [33]:
arr1

array([[5, 4, 2, 6],
       [5, 9, 9, 1],
       [9, 7, 4, 3]])

In [34]:
arr2

array([[2, 7, 9, 6],
       [8, 4, 9, 8],
       [9, 2, 9, 9]])

In [35]:
arr1+arr2

array([[ 7, 11, 11, 12],
       [13, 13, 18,  9],
       [18,  9, 13, 12]])

In [36]:
arr1*arr2

array([[10, 28, 18, 36],
       [40, 36, 81,  8],
       [81, 14, 36, 27]])

In [37]:
arr1/arr2

array([[2.5       , 0.57142857, 0.22222222, 1.        ],
       [0.625     , 2.25      , 1.        , 0.125     ],
       [1.        , 3.5       , 0.44444444, 0.33333333]])

In [38]:
arr1-arr2

array([[ 3, -3, -7,  0],
       [-3,  5,  0, -7],
       [ 0,  5, -5, -6]])

In [39]:
arr1%arr2

array([[1, 4, 2, 0],
       [5, 1, 0, 1],
       [0, 1, 4, 3]])

In [40]:
arr1**arr2

array([[       25,     16384,       512,     46656],
       [   390625,      6561, 387420489,         1],
       [387420489,        49,    262144,     19683]])

In [41]:
arr1 &arr2

array([[0, 4, 0, 6],
       [0, 0, 9, 0],
       [9, 2, 0, 1]])

In [42]:
arr1

array([[5, 4, 2, 6],
       [5, 9, 9, 1],
       [9, 7, 4, 3]])

In [43]:
arr2

array([[2, 7, 9, 6],
       [8, 4, 9, 8],
       [9, 2, 9, 9]])

In [44]:
~arr1

array([[ -6,  -5,  -3,  -7],
       [ -6, -10, -10,  -2],
       [-10,  -8,  -5,  -4]])

In [45]:
arr1|arr2

array([[ 7,  7, 11,  6],
       [13, 13,  9,  9],
       [ 9,  7, 13, 11]])

In [46]:
arr1>arr2

array([[ True, False, False, False],
       [False,  True, False, False],
       [False,  True, False, False]])

In [47]:
#numpy - string

In [48]:
arr = np.array(['prakash','kumar'])

In [49]:
arr

array(['prakash', 'kumar'], dtype='<U7')

In [50]:
np.char.upper(arr)

array(['PRAKASH', 'KUMAR'], dtype='<U7')

In [52]:
np.char.title(arr)

array(['Prakash', 'Kumar'], dtype='<U7')

In [53]:
np.char.capitalize(arr)

array(['Prakash', 'Kumar'], dtype='<U7')

In [54]:
#numpy - mathematical function

In [55]:
arr1

array([[5, 4, 2, 6],
       [5, 9, 9, 1],
       [9, 7, 4, 3]])

In [56]:
np.sin(arr1)

array([[-0.95892427, -0.7568025 ,  0.90929743, -0.2794155 ],
       [-0.95892427,  0.41211849,  0.41211849,  0.84147098],
       [ 0.41211849,  0.6569866 , -0.7568025 ,  0.14112001]])

In [57]:
np.cos(arr1)

array([[ 0.28366219, -0.65364362, -0.41614684,  0.96017029],
       [ 0.28366219, -0.91113026, -0.91113026,  0.54030231],
       [-0.91113026,  0.75390225, -0.65364362, -0.9899925 ]])

In [59]:
np.tan(arr1)

array([[-3.38051501,  1.15782128, -2.18503986, -0.29100619],
       [-3.38051501, -0.45231566, -0.45231566,  1.55740772],
       [-0.45231566,  0.87144798,  1.15782128, -0.14254654]])

In [60]:
np.tanh(arr1)

array([[0.9999092 , 0.9993293 , 0.96402758, 0.99998771],
       [0.9999092 , 0.99999997, 0.99999997, 0.76159416],
       [0.99999997, 0.99999834, 0.9993293 , 0.99505475]])

In [61]:
np.log10(arr1)

array([[0.69897   , 0.60205999, 0.30103   , 0.77815125],
       [0.69897   , 0.95424251, 0.95424251, 0.        ],
       [0.95424251, 0.84509804, 0.60205999, 0.47712125]])

In [62]:
np.power(arr1 , 2)

array([[25, 16,  4, 36],
       [25, 81, 81,  1],
       [81, 49, 16,  9]])

In [63]:
np.mean(arr1)

5.333333333333333

In [66]:
np.median(arr1)

5.0

In [67]:
np.std(arr1)

2.6246692913372702

In [68]:
np.var(arr1)

6.888888888888889

In [69]:
np.min(arr1)

1

In [70]:
np.max(arr1)

9