In [1]:
import numpy as np

In [2]:
l = [1,2,3,4]

In [3]:
ar = np.array(l)

In [4]:
ar

array([1, 2, 3, 4])

In [5]:
type(ar)

numpy.ndarray

In [6]:
np.array([[1,2],[3,5]])

array([[1, 2],
       [3, 5]])

In [7]:
np.asarray(l)

array([1, 2, 3, 4])

In [8]:
a = [2,3,4,5]

In [9]:
np.asanyarray(a)

array([2, 3, 4, 5])

In [10]:
b= np.matrix(l)

In [11]:
b

matrix([[1, 2, 3, 4]])

In [12]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [13]:
a = np.array(l)

In [14]:
a

array([1, 2, 3, 4])

In [15]:
c = a

In [16]:
c

array([1, 2, 3, 4])

In [17]:
c[0] = 100

In [18]:
c

array([100,   2,   3,   4])

In [19]:
a

array([100,   2,   3,   4])

In [20]:
d = np.copy(a)

In [21]:
d

array([100,   2,   3,   4])

In [22]:
a

array([100,   2,   3,   4])

In [23]:
a[1] = 400

In [24]:
a

array([100, 400,   3,   4])

In [25]:
d

array([100,   2,   3,   4])

In [26]:
np.fromfunction(lambda i,j : i == j , (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [27]:
np.fromfunction(lambda i,j : i * j , (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [28]:
iterable = (i*i for i in range(5))

In [29]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [30]:
np.fromstring('345 324', sep= ' ')

array([345., 324.])

In [31]:
np.fromstring('4,5' , sep = ',')

array([4., 5.])

In [32]:
#numpy - Datatype

In [33]:
l = [2,3,45,6,8]

In [34]:
ar = np.array(l)

In [35]:
ar

array([ 2,  3, 45,  6,  8])

In [36]:
ar.ndim

1

In [37]:
ar2 = np.array([[1,2,3],[5,6,7]])

In [38]:
ar2.ndim

2

In [39]:
ar.size

5

In [40]:
ar2.size

6

In [41]:
ar.shape

(5,)

In [42]:
ar2.shape

(2, 3)

In [43]:
ar.dtype

dtype('int64')

In [44]:
ar2.dtype

dtype('int64')

In [45]:
ar22 = np.array([(1.5,45,45),(23,45,99)])

In [46]:
ar22

array([[ 1.5, 45. , 45. ],
       [23. , 45. , 99. ]])

In [47]:
ar22.dtype

dtype('float64')

In [48]:
list(range(5))

[0, 1, 2, 3, 4]

In [49]:
list(range(0.1,5))

TypeError: 'float' object cannot be interpreted as an integer

In [50]:
np.arange(2.5,9.5,0.2)

array([2.5, 2.7, 2.9, 3.1, 3.3, 3.5, 3.7, 3.9, 4.1, 4.3, 4.5, 4.7, 4.9,
       5.1, 5.3, 5.5, 5.7, 5.9, 6.1, 6.3, 6.5, 6.7, 6.9, 7.1, 7.3, 7.5,
       7.7, 7.9, 8.1, 8.3, 8.5, 8.7, 8.9, 9.1, 9.3])

In [51]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [52]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [53]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [54]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [55]:
ar4 = np.zeros((3,4,2,3))

In [56]:
ar4.ndim

4

In [57]:
np.ones(4)

array([1., 1., 1., 1.])

In [58]:
on = np.ones((2,2,3))

In [59]:
on+5

array([[[6., 6., 6.],
        [6., 6., 6.]],

       [[6., 6., 6.],
        [6., 6., 6.]]])

In [60]:
on*4

array([[[4., 4., 4.],
        [4., 4., 4.]],

       [[4., 4., 4.],
        [4., 4., 4.]]])

In [61]:
np.empty((3,4))

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [62]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [63]:
np.linspace(2,4 , 20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [65]:
np.logspace(2,5,10,base= 2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [67]:
arr = np.random.randn(3,4)

In [68]:
import pandas as pd

In [69]:
pd.DataFrame(arr)

0         1         2         3
0 -1.546413 -1.708702  0.305105 -2.043317
1  0.251956  1.023157 -1.120148  0.510675
2  1.621130 -0.657374 -1.080590  0.986666

In [71]:
np.random.rand(3,4)

array([[0.73907573, 0.38813221, 0.50300361, 0.27194878],
       [0.78090805, 0.07356765, 0.07343818, 0.06642135],
       [0.01960881, 0.3035401 , 0.52886903, 0.56216793]])

In [73]:
np.random.randint(1,110 , (3,4))

array([[  6,   9,   3, 108],
       [ 17,  44,  23,  88],
       [ 51,  60,  40,  36]])

In [74]:
arr = np.random.rand(3,4)

In [75]:
arr

array([[0.22529224, 0.06437029, 0.15778071, 0.77594284],
       [0.76544236, 0.73170371, 0.8645833 , 0.09258534],
       [0.93293094, 0.28501848, 0.53365816, 0.54992944]])

In [76]:
arr.reshape(6,2)

array([[0.22529224, 0.06437029],
       [0.15778071, 0.77594284],
       [0.76544236, 0.73170371],
       [0.8645833 , 0.09258534],
       [0.93293094, 0.28501848],
       [0.53365816, 0.54992944]])

In [78]:
arr1 = arr.reshape(6,-12324534)

In [79]:
arr1

array([[0.22529224, 0.06437029],
       [0.15778071, 0.77594284],
       [0.76544236, 0.73170371],
       [0.8645833 , 0.09258534],
       [0.93293094, 0.28501848],
       [0.53365816, 0.54992944]])

In [81]:
arr1[1][1]

0.7759428352674141

In [83]:
arr1[2:5 , 1]

array([0.73170371, 0.09258534, 0.28501848])

In [85]:
arr = np.random.randint(1,100 , (5,5))

In [86]:
arr

array([[26, 64, 58, 77, 92],
       [48, 59, 64, 40,  4],
       [51, 35, 68, 49, 94],
       [13, 14,  5, 30, 60],
       [52, 91, 50, 56, 84]])

In [88]:
arr[arr>50]

array([64, 58, 77, 92, 59, 64, 51, 68, 94, 60, 52, 91, 56, 84])

In [89]:
arr

array([[26, 64, 58, 77, 92],
       [48, 59, 64, 40,  4],
       [51, 35, 68, 49, 94],
       [13, 14,  5, 30, 60],
       [52, 91, 50, 56, 84]])

In [97]:
arr[2:4 , (1,2)]

array([[35, 68],
       [14,  5]])

In [99]:
arr[0][0] = 1000

In [100]:
arr

array([[1000,   64,   58,   77,   92],
       [  48,   59,   64,   40,    4],
       [  51,   35,   68,   49,   94],
       [  13,   14,    5,   30,   60],
       [  52,   91,   50,   56,   84]])

In [101]:
arr1 = np.random.randint(1,3 , (3,3))
arr2 = np.random.randint(1,3 , (3,3))

In [102]:
arr1

array([[1, 2, 2],
       [2, 1, 1],
       [1, 1, 1]])

In [103]:
arr2

array([[1, 1, 2],
       [2, 2, 1],
       [1, 2, 2]])

In [104]:
arr1+arr2

array([[2, 3, 4],
       [4, 3, 2],
       [2, 3, 3]])

In [105]:
arr1*arr2

array([[1, 2, 4],
       [4, 2, 1],
       [1, 2, 2]])

In [106]:
arr1-arr2

array([[ 0,  1,  0],
       [ 0, -1,  0],
       [ 0, -1, -1]])

In [107]:
arr1/arr2

array([[1. , 2. , 1. ],
       [1. , 0.5, 1. ],
       [1. , 0.5, 0.5]])

In [108]:
arr1@arr2

array([[7, 9, 8],
       [5, 6, 7],
       [4, 5, 5]])

In [109]:
arr1/0

/tmp/ipykernel_166/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [110]:
arr1+100

array([[101, 102, 102],
       [102, 101, 101],
       [101, 101, 101]])

In [111]:
arr1**2

array([[1, 4, 4],
       [4, 1, 1],
       [1, 1, 1]])

In [112]:
#numpy broadcasting

In [114]:
arr = np.zeros((4,4))

In [115]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [116]:
row = np.array([1,2,3,4])

In [118]:
row

array([1, 2, 3, 4])

In [119]:
arr+row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [120]:
row.T

array([1, 2, 3, 4])

In [128]:
col = np.array([[1,2,3,4]])

In [129]:
col

array([[1, 2, 3, 4]])

In [130]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [132]:
arr+col.T

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [135]:
arr1 = np.random.randint(1,4 , (3,4))

In [136]:
arr1

array([[3, 3, 2, 2],
       [1, 3, 2, 3],
       [3, 1, 2, 2]])

In [137]:
np.sqrt(arr1)

array([[1.73205081, 1.73205081, 1.41421356, 1.41421356],
       [1.        , 1.73205081, 1.41421356, 1.73205081],
       [1.73205081, 1.        , 1.41421356, 1.41421356]])

In [138]:
np.exp(arr1)

array([[20.08553692, 20.08553692,  7.3890561 ,  7.3890561 ],
       [ 2.71828183, 20.08553692,  7.3890561 , 20.08553692],
       [20.08553692,  2.71828183,  7.3890561 ,  7.3890561 ]])

In [139]:
np.log2(arr1)

array([[1.5849625, 1.5849625, 1.       , 1.       ],
       [0.       , 1.5849625, 1.       , 1.5849625],
       [1.5849625, 0.       , 1.       , 1.       ]])